=== MaxDartois/Cours-M2-TNAH/Edition scientifique à l'ère du numérique/Exercices XML/Misanthrope/misanthrope.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!ELEMENT piece (titre*, acte*, scene*, casting*, tourDeParole*, didascalie*, vers*) >
<!ELEMENT titre (#PCDATA | acte | scene | tourDeParole | vers)* >
<!ELEMENT acte (#PCDATA | titre | scene | tourDeParole | vers)* >
<!ELEMENT scene (#PCDATA | titre | casting | tourDeParole | didascalie | vers)* >
<!ELEMENT casting (#PCDATA) >
<!ELEMENT tourDeParole (#PCDATA | didascalie)* >
<!ELEMENT didascalie (#PCDATA)* >
<!ELEMENT vers (#PCDATA) >


<!ATTLIST titre type (acte | scene) #REQUIRED >

=== MaxDartois/Cours-M2-TNAH/Edition scientifique à l'ère du numérique/Exercices XML/Misanthrope/misanthrope.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE piece SYSTEM "misanthrope.dtd">
<piece>
    <titre type="acte">LE MISANTHROPE.</titre>
        <acte>
        <titre type="acte">ACTE PREMIER</titre>
        <scene>
            <titre type="scene">SCÈNE 1.</titre>
            <casting>PHILINTE, ALCESTE</casting>
            <tourDeParole>PHILINTE.</tourDeParole>
            <vers>Qu'est-ce donc? qu'avez-vous ?</vers>
            <tourDeParole>ALCESTE<didascalie>, assis</didascalie>.</tourDeParole>
            <vers>Laissez-moi, je vous prie.</vers>
            <tourDeParole>PHILINTE.</tourDeParole>
            <vers>Mais encor, dites-moi, quelle bizarrerie....</vers>
            <tourDeParole>ALCESTE.</tourDeParole>
            <vers>Laissez-moi là, vous dis-je, et courez vous cacher.</vers>
            <tourDeParole>PHILINTE.</tourDeParole>
            <vers>Mais on entend les gens au moins sans se fâcher.</vers>
            <tourDeParole>ALCESTE.</tourDeParole>
            <vers>Moi, je veux me fâcher, et ne veux point entendre.</vers>
            <tourDeParole>PHILINTE</tourDeParole>
            <vers>Dans vos brusques chagrins je ne puis vous comprendre,</vers>
            <vers>Et quoique amis enfin, je suis tout des premiers....</vers>
            <tourDeParole>ALCESTE<didascalie>, se levant brusquement</didascalie>.</tourDeParole>
            <vers>Moi, votre ami? Rayez cela de vos papiers.</vers>
            <vers>J'ai fait jusques ici profession de l'être,</vers>
            <vers>Mais, après ce qu'en vous je viens de voir paraître,</vers>
        </scene>
    </acte>
</piece>
